apiVersion: v1
kind: Service
metadata:
  name: pitstop-vehicle-database-service
spec:
  ports:
   - name: mysql
     port: 3306
     targetPort: 3306
  selector:
    app: pitstop-vehicle-database
  type: ClusterIP