apiVersion: v1
kind: Service
metadata:
  name: pitstop-vehicle-service
  namespace: pitstop
spec:
  selector:
    app: vehicle-service
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP
