apiVersion: v1
kind: ConfigMap
metadata:
  name: pitstop-vehicle-database-configmap
data:
  MYSQL_DATABASE: pitstop
  MYSQL_ROOT_PASSWORD: pitstop-user
  MYSQL_USER: pitstop-user
  MYSQL_PASSWORD: pitstop-user