apiVersion: v1
kind: PersistentVolume
metadata:
  name: vehicle-db-volume
  labels:
    type: local
spec:
  storageClassName: "standard"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"